spring.application.name=ADS_Data_Persistence

spring.datasource.url=jdbc:postgresql://localhost:5433/ads_dental_surgery
spring.datasource.username=postgres
spring.datasource.password=0987654321

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
